name: Test code

on:
  push:
    branches: [main, feature/*]
permissions:
  contents: read

jobs:
  run:
    strategy:
      matrix:
        go: [ ${{ vars.GO_VERSION }} ]
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x -coverprofile=benchmark.txt ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        continue-on-error: true  # we don't care if it fails
        with:
          token: ${{secrets.CODECOV_TOKEN}}  # set in repository settings
          files: ./coverage.txt,./benchmark.txt   # file from the previous step
          fail_ci_if_error: false